name: C/C++ CI

on:
  push:
    branches: [ workflows ]
  pull_request:
    branches: [ workflows ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ashutoshvarma/action-cmake-build@v1
