name: CMake Build Matrix

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - run: pip install minecraft-data
      - run: sudo apt-get install ninja-build libboost1.71-all-dev libbotan-2-dev
      - run: cmake . -G Ninja
        env:
          CC: gcc-10
          CXX: g++-10
      - run: cmake --build . --target rikerbot_all
      - run: python setup.py bdist_wheel

  windows:
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - run: pip install minecraft-data
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: zlib:x64-windows-static botan:x64-windows-static
          vcpkgGitCommitId: ff7113a7c6dcb38a4cbf144052b3691b348ef4da
      - run: cmake . -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake -DBOOST_ROOT=$BOOST_ROOT_1_72_0 -DBoost_INCLUDE_DIR=$BOOST_ROOT_1_72_0\include
        shell: bash
      - run: cmake --build . --target rikerbot_all
      - run: python setup.py bdist_wheel
