name: CMake Build Matrix

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - run: pip install minecraft-data
      - run: sudo apt-get install ninja-build libboost1.71-all-dev libbotan-2-dev
      - run: cmake . -G Ninja
      - run: cmake --build . --target rikerbot_all
      - run: python setup.py bdist_whell
