name: CMake Build Matrix

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - run: pip install minecraft-data
      - run: sudo apt-get install ninja-build libboost1.71-all-dev libbotan-2-dev
      - run: cmake . -G Ninja
        env:
          CC: gcc-10
          CXX: g++-10
      - run: cmake --build . --target rikerbot_all
      - run: python setup.py bdist_wheel

  windows:
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - run: pip install minecraft-data
      - run: vcpkg install zlib botan:x64-windows-static
      - run: cmake . -DBOOST_ROOT="${BOOST_ROOT_1_72_0}" -DBoost_INCLUDE_DIR="${BOOST_ROOT_1_72_0}/include"
      - run: cmake --build . --target rikerbot_all
      - run: python setup.py bdist_wheel
